package by.epam.stock.command;

public enum CommandName {
GET_PRODUCT, GET_SORTED_PRODUCT,  SHOW_PRODUCT_BY_NAME,  SHOW_PRODUCT_BY_CODE,  SHOW_PRODUCT_BY_ANNOTATION,
SHOW_PRODUCT_BY_PRODUCTDATE,  SHOW_PRODUCT_BY_NAME_AND_CODE,  SHOW_PRODUCT_BY_ANNOTATION_CONTAIN, ADD_PRODUCT

}

